package com.asakusafw.yaess.v2;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kuenishi' at '5/2/16 3:53 PM' with Gradle 2.9
 *
 * @author kuenishi, @date 5/2/16 3:53 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
