package com.asakusafw.yaess.v2;

import com.asakusafw.yaess.v2.Library;
import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'kuenishi' at '5/2/16 3:53 PM' with Gradle 2.9
 *
 * @author kuenishi, @date 5/2/16 3:53 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
